[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
